- id: '1590245503931'
  alias: Notify if rain
  description: ''
  trigger:
  - entity_id: weather.kpvu_hourly
    platform: state
    to: rainy
  action:
  - data:
      message: It might be raining outside
    service: notify.hangouts
- id: '1590247052501'
  alias: Reconnect hangout
  description: ''
  trigger:
  - minutes: '1'
    platform: time_pattern
  condition: []
  action:
  - data: {}
    service: hangouts.reconnect
