
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.18.0.0/24 # nginx container ip
    - 192.168.1.0/24 #Router IP

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

frontend:
  themes: !include_dir_merge_named themes

logger:
  default: warning

logbook:
  exclude:
    entities:
      - sensor.wan_in
      - sensor.wan_out
      - sensor.mail_updated
      - sensor.wan_in_hour
      - sensor.wan_in_day
      - sensor.wan_in_month
      - sensor.wan_gb
      - sensor.wan_mb
      - sensor.wan_out_gb
      - sensor.wan_in_gb
      - sensor.wan_out_mb
      - sensor.wan_in_mb
      - sensor.utility_internet_daily
      - sensor.utility_internet_hourly
      - sensor.utility_internet_monthly
      - sensor.router_up_time
      - sensor.router_up_time_hours
      - sensor.router_up_time_days

history:
  exclude:
    entities:
      - sensor.time
      - sensor.date
      - sensor.date_time
      - sensor.date_time_utc
      - sensor.date_time_iso
      - sensor.time_date
      - sensor.time_utc
      - sensor.internet_time
      - sensor.wan_in
      - sensor.wan_out
      - sensor.wan_in_hour
      - sensor.wan_in_day
      - sensor.wan_in_month
      - sensor.mail_updated
      - sensor.wan_gb
      - sensor.wan_mb
      - sensor.wan_out_gb
      - sensor.wan_in_gb
      - sensor.wan_out_mb
      - sensor.wan_in_mb
      - sensor.utility_internet_daily
      - sensor.utility_internet_hourly
      - sensor.utility_internet_monthly
      - sensor.router_up_time
      - sensor.router_up_time_hours
      - sensor.router_up_time_days

recorder:
  exclude:
    entities:
      - sensor.time
      - sensor.date
      - sensor.date_time
      - sensor.date_time_utc
      - sensor.date_time_iso
      - sensor.time_date
      - sensor.time_utc
      - sensor.internet_time
      - !secret mobile_app_1_location
      - !secret mobile_app_2_location

homeassistant:
  external_url: !secret external_url
  internal_url: !secret internal_url
  customize: !include customize.yaml

panel_iframe:
 nodered:
   title: 'Node-Red'
   icon: 'mdi:shuffle-variant'
   url: !secret nodered_url
 unifi:
   title: 'Unifi'
   icon: 'mdi:wifi'
   url: !secret unifi_url
 roborock:
   title: 'Roborock'
   icon: 'mdi:robot-vacuum'
   url: !secret roborock_url

wake_on_lan:

google_assistant:
  project_id: debian-home-server
  service_account: !include debian-home-server-token-dfbbae81fb3b.json
  report_state: true
  exposed_domains:
    - switch
    - light
    - vacuum
    - media_player
    - cover
    - lock
    - group
    - scene

zwave:
  usb_path: /dev/ttyUSB0
  network_key: !secret zwave_key

zha:
  database_path: /config/zigbee.db

webostv:
- name: Living Room TV
  host: 192.168.1.44
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: 20-17-42-20-4B-EB

notify:
  - platform: group
    name: all_phone_app
    services:
      - service: !secret mobile_app_1_phone
      - service: !secret mobile_app_2_phone
      - service: !secret mobile_app_3_phone

mqtt:
  broker: 192.168.1.38
  port: 1883
  client_id: home-assistant
  username: !secret mqtt_user
  password: !secret mqtt_pwd
  discovery: true
  discovery_prefix: homeassistant

camera:
  - platform: local_file
    file_path: !secret mail_images_path
    name: mail_usps

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'
  # - platform: govee_ble_hci
  #   govee_devices:
      # - mac: !secret govee_humidity_sensor_mac_1
      #   name: Bedroom
      # - mac: !secret govee_humidity_sensor_mac_2
      #   name: Bathroom
      #   hcitool_active: true
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: disk_use
        arg: /
      - type: disk_free
        arg: /
      - type: processor_use
      - type: memory_use_percent
      - type: memory_use
      - type: memory_free
  - platform: snmp
    version: '3'
    name: wan_in
    host: 192.168.1.1
    baseoid: 1.3.6.1.2.1.31.1.1.1.6.4
    username: !secret snmp_username
    auth_key: !secret snmp_auth_key
    auth_protocol: !secret snmp_auth_protocol
    priv_key: !secret snmp_priv_key
    priv_protocol: !secret snmp_priv_protocol
    accept_errors: true
    scan_interval: 60
  - platform: snmp
    version: '3'
    name: wan_out
    host: 192.168.1.1
    baseoid: 1.3.6.1.2.1.31.1.1.1.10.4
    username: !secret snmp_username
    auth_key: !secret snmp_auth_key
    auth_protocol: !secret snmp_auth_protocol
    priv_key: !secret snmp_priv_key
    priv_protocol: !secret snmp_priv_protocol
    accept_errors: true
    scan_interval: 60
  - platform: snmp
    version: '3'
    name: router_uptime
    host: 192.168.1.1
    baseoid: 1.3.6.1.2.1.1.3.0
    unit_of_measurement: 'minutes'
    value_template: '{{((value | int) / 6000) | int}}'
    username: !secret snmp_username
    auth_key: !secret snmp_auth_key
    auth_protocol: !secret snmp_auth_protocol
    priv_key: !secret snmp_priv_key
    priv_protocol: !secret snmp_priv_protocol
    accept_errors: true
    scan_interval: 60
  - platform: template
    sensors:
      back_door_status:
        friendly_name: Back door status
        value_template: >-
          {{ state_attr('lock.back_door', 'lock_status') }}
      minh_home:
        value_template: >-
          {{ is_state('device_tracker.phone_m_4a5g', 'home') or is_state('person.minh', 'home') }}
      router_up_time_hours:
        friendly_name: 'Router uptime - Hours'
        value_template: >-
          {{ ((states('sensor.router_uptime')|int) / 60) | int }}
      router_up_time_days:
        friendly_name: 'Router uptime - Days'
        value_template: >-
          {{ ((states('sensor.router_up_time_hours')|int) / 24) | int }}
      wan_in_mb:
        value_template: >-
          {{ states('sensor.wan_in')|float/1000000 }}
      wan_out_mb:
        value_template: >-
          {{ states('sensor.wan_out')|float/1000000 }}
      wan_in_gb:
        value_template: >-
          {{ states('sensor.wan_in_mb')|float/1000 }}
      wan_out_gb:
        value_template: >-
          {{ states('sensor.wan_out_mb')|float/1000 }}
      wan_mb:
        value_template: >-
          {{ states('sensor.wan_in_mb')|float + states('sensor.wan_out_mb')|float }}
      wan_gb:
        value_template: >-
          {{ states('sensor.wan_in_gb')|float + states('sensor.wan_out_gb')|float }}
      internet_hourly:
        friendly_name: Hourly Internet Usage
        unit_of_measurement: MB
        value_template: >-
          {{ (states('sensor.utility_internet_hourly')|float)|round(2) }}
      internet_daily:
        friendly_name: Daily Internet Usage
        unit_of_measurement: GB
        value_template: >-
          {{ (states('sensor.utility_internet_daily')|float)|round(2) }}
      internet_monthly:
        friendly_name: Monthly Internet Usage
        unit_of_measurement: GB
        value_template: >-
          {{ (states('sensor.utility_internet_monthly')|float)|round(2) }}
  - platform: command_line
    name: IP Address
    command: "dig +short myip.opendns.com @resolver1.opendns.com"
    scan_interval: 7200

  - platform: statistics
    name: wan_in_hour
    entity_id: sensor.wan_in
    max_age:
      hours: 1
  - platform: statistics
    name: wan_in_day
    entity_id: sensor.wan_in
    max_age:
      days: 1
  - platform: statistics
    name: wan_in_month
    entity_id: sensor.wan_in
    max_age:
      days: 31

utility_meter:
  utility_internet_hourly:
    source: sensor.wan_mb
    cycle: hourly
    offset:
      hours: 0
      minutes: 0
  utility_internet_daily:
    source: sensor.wan_gb
    cycle: daily
    offset:
      hours: 0
      minutes: 0
  utility_internet_monthly:
    source: sensor.wan_gb
    cycle: monthly
    offset:
      days: 0
      hours: 0
      minutes: 0
