
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.18.0.0/24 # nginx container ip
    - 192.168.1.0/24 #Router IP

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

frontend:
  themes: !include_dir_merge_named themes

media_source:

logger:
  default: warning

logbook:
  exclude:
    entities:
      - sensor.wan_in
      - sensor.wan_out
      - sensor.mail_updated
      - sensor.wan_in_hour
      - sensor.wan_in_day
      - sensor.wan_in_month
      - sensor.wan_gb
      - sensor.wan_mb
      - sensor.wan_out_gb
      - sensor.wan_in_gb
      - sensor.wan_out_mb
      - sensor.wan_in_mb
      - sensor.utility_internet_daily
      - sensor.utility_internet_hourly
      - sensor.utility_internet_monthly
      - sensor.router_up_time
      - sensor.router_up_time_hours
      - sensor.router_up_time_days
      - sensor.octoprint_print_time_left
      - sensor.octoprint_print_time
      - sensor.octoprint_print_progress
      - sensor.octoprint_slicing_progress
      - sensor.octoprint_current_z
      - sensor.octoprint_print_time_done_at

history:
  exclude:
    entities:
      - sensor.time
      - sensor.date
      - sensor.date_time
      - sensor.date_time_utc
      - sensor.date_time_iso
      - sensor.time_date
      - sensor.time_utc
      - sensor.internet_time
      - sensor.wan_in
      - sensor.wan_out
      - sensor.wan_in_hour
      - sensor.wan_in_day
      - sensor.wan_in_month
      - sensor.mail_updated
      - sensor.wan_gb
      - sensor.wan_mb
      - sensor.wan_out_gb
      - sensor.wan_in_gb
      - sensor.wan_out_mb
      - sensor.wan_in_mb
      - sensor.utility_internet_daily
      - sensor.utility_internet_hourly
      - sensor.utility_internet_monthly
      - sensor.router_up_time
      - sensor.router_up_time_hours
      - sensor.router_up_time_days
      - sensor.octoprint_print_time_left
      - sensor.octoprint_print_time
      - sensor.octoprint_print_progress
      - sensor.octoprint_slicing_progress
      - sensor.octoprint_current_z
      - sensor.octoprint_print_time_done_at
    entity_globs:
      - input_boolean.plant*
      - input_number.plant*
      - input_datetime.plant*
      - sensor.mail*
      - sensor.disk*

recorder:
  exclude:
    entities:
      - sensor.time
      - sensor.date
      - sensor.date_time
      - sensor.date_time_utc
      - sensor.date_time_iso
      - sensor.time_date
      - sensor.time_utc
      - sensor.internet_time
      - !secret mobile_app_1_location
      - !secret mobile_app_2_location
    entity_globs:  
      - sensor.*phone*
      - sensor.*pixel*
      - sensor.hp_officejet*

homeassistant:
  external_url: !secret external_url
  internal_url: !secret internal_url
  customize: !include customize.yaml

panel_iframe:
 nodered:
   title: 'Node-Red'
   icon: 'mdi:shuffle-variant'
   url: !secret nodered_url
 octoprint:
   title: 'Octoprint'
   icon: 'mdi:printer-3d'
   url: !secret octoprint_url
 zwave:
   title: 'Zwave'
   icon: 'mdi:z-wave'
   url: !secret zwave_url
 unifi:
   title: 'Unifi'
   icon: 'mdi:wifi'
   url: !secret unifi_url
 roborock:
   title: 'Roborock'
   icon: 'mdi:robot-vacuum'
   url: !secret roborock_url

wake_on_lan:

stream:

camera:
- platform: mjpeg
  name: Voxelab Aquila stream
  still_image_url: !secret octoprint_still_image_url
  mjpeg_url: !secret octoprint_mjpeg_url

google_assistant:
  project_id: debian-home-server
  service_account: !include debian-home-server-token-dfbbae81fb3b.json
  report_state: true
  exposed_domains:
    - switch
    - light
    - vacuum
    - media_player
    - cover
    - lock
    - group
    - scene

zha:
  database_path: /config/zigbee.db

webostv:
- name: Living Room TV
  host: 192.168.1.44
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: 20-17-42-20-4B-EB

notify:
  - platform: html5
    name: chrome
    vapid_pub_key: !secret html_pub_key
    vapid_prv_key: !secret html_private_key
    vapid_email: !secret html_email

  - platform: group
    name: all_phone_app
    services:
      - service: !secret mobile_app_1_phone
      - service: !secret mobile_app_2_phone
      - service: chrome

  - platform: group
    name: m_only
    services:
      - service: !secret mobile_app_1_phone
      - service: chrome

mqtt:
  broker: 192.168.1.38
  port: 1883
  client_id: home-assistant
  username: !secret mqtt_user
  password: !secret mqtt_pwd
  discovery: true
  discovery_prefix: homeassistant

winix:
  username: !secret winix_email
  password: !secret winix_password

sensor:
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_utc'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'
# - platform: govee_ble_hci
#   govee_devices:
    # - mac: !secret govee_humidity_sensor_mac_1
    #   name: Bedroom
    # - mac: !secret govee_humidity_sensor_mac_2
    #   name: Bathroom
    #   hcitool_active: true
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_use
      arg: /
    - type: disk_free
      arg: /
    - type: processor_use
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
- platform: snmp
  version: '3'
  name: wan_in
  host: 192.168.1.1
  baseoid: 1.3.6.1.2.1.31.1.1.1.6.4
  username: !secret snmp_username
  auth_key: !secret snmp_auth_key
  auth_protocol: !secret snmp_auth_protocol
  priv_key: !secret snmp_priv_key
  priv_protocol: !secret snmp_priv_protocol
  accept_errors: true
  scan_interval: 60
- platform: snmp
  version: '3'
  name: wan_out
  host: 192.168.1.1
  baseoid: 1.3.6.1.2.1.31.1.1.1.10.4
  username: !secret snmp_username
  auth_key: !secret snmp_auth_key
  auth_protocol: !secret snmp_auth_protocol
  priv_key: !secret snmp_priv_key
  priv_protocol: !secret snmp_priv_protocol
  accept_errors: true
  scan_interval: 60
- platform: snmp
  version: '3'
  name: router_uptime
  host: 192.168.1.1
  baseoid: 1.3.6.1.2.1.1.3.0
  unit_of_measurement: 'minutes'
  value_template: '{{((value | int) / 6000) | int}}'
  username: !secret snmp_username
  auth_key: !secret snmp_auth_key
  auth_protocol: !secret snmp_auth_protocol
  priv_key: !secret snmp_priv_key
  priv_protocol: !secret snmp_priv_protocol
  accept_errors: true
  scan_interval: 60
- platform: command_line
  name: IP Address
  command: "dig +short myip.opendns.com @resolver1.opendns.com"
  scan_interval: 7200

- platform: statistics
  name: wan_in_hour
  entity_id: sensor.wan_in
  max_age:
    hours: 1
- platform: statistics
  name: wan_in_day
  entity_id: sensor.wan_in
  max_age:
    days: 1
- platform: statistics
  name: wan_in_month
  entity_id: sensor.wan_in
  max_age:
    days: 31
      
sensor template sensors: !include template-sensors.yaml

utility_meter:
  utility_internet_hourly:
    source: sensor.wan_mb
    cycle: hourly
    offset:
      hours: 0
      minutes: 0
  utility_internet_daily:
    source: sensor.wan_gb
    cycle: daily
    offset:
      hours: 0
      minutes: 0
  utility_internet_monthly:
    source: sensor.wan_gb
    cycle: monthly
    offset:
      days: 0
      hours: 0
      minutes: 0
