
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.19.0.3 # nginx container ip
    - 192.168.1.0/24 #Router IP

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

history:
  exclude:
    entities:
      - sensor.time
      - sensor.date
      - sensor.date_time
      - sensor.date_time_utc
      - sensor.date_time_iso
      - sensor.time_date
      - sensor.time_utc
      - sensor.internet_time

recorder:
  exclude:
    entities:
      - sensor.time
      - sensor.date
      - sensor.date_time
      - sensor.date_time_utc
      - sensor.date_time_iso
      - sensor.time_date
      - sensor.time_utc
      - sensor.internet_time

homeassistant:
  external_url: !secret external_url
  internal_url: !secret internal_url

panel_iframe:
 nodered:
   title: 'Node-Red'
   icon: 'mdi:shuffle-variant'
   url: !secret nodered_url
 unifi:
   title: 'Unifi'
   icon: 'mdi:wifi'
   url: !secret unifi_url
 roborock:
   title: 'Roborock'
   icon: 'mdi:robot-vacuum'
   url: !secret roborock_url

wake_on_lan:

google_assistant:
  project_id: debian-home-server

notify:
  - platform: discord
    name: discord
    token: !secret discord_token
  - platform: hangouts
    name: hangouts
    default_conversations:
      - id: "UgzF-v3X32B8mB9cN4d4AaABAagB8f-iAg"
  - platform: group
    name: all_phone_app
    services:
      - service: !secret mobile_app_1_phone
      - service: !secret mobile_app_2_phone

webostv:
  - name: Living Room TV
    host: 192.168.1.44
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: 20-17-42-20-4B-EB

mqtt:
  broker: 192.168.1.38
  port: 1883
  client_id: home-assistant
  username: !secret mqtt_user
  password: !secret mqtt_pwd
  discovery: true
  discovery_prefix: homeassistant

camera:
  - platform: local_file
    file_path: !secret mail_images_path
    name: mail_usps

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: disk_use
        arg: /
      - type: disk_free
        arg: /
      - type: processor_use
      - type: memory_use_percent
      - type: memory_use
      - type: memory_free

binary_sensor:
  - platform: template
    sensors:
      minh_home:
        friendly_name: "Minh Home"
        value_template: >-
          {{ is_state('device_tracker.phone_m', 'home') or is_state('person.minh', 'home') }}