- platform: template
  sensors:
    back_door_status:
      friendly_name: Back door status
      value_template: >-
        {{ state_attr('lock.back_door', 'lock_status') }}

    minh_home:
      value_template: >-
        {{ is_state('device_tracker.phone_m_4a5g', 'home') or is_state('person.minh', 'home') }}

    router_up_time_hours:
      friendly_name: 'Router uptime - Hours'
      value_template: >-
        {{ ((states('sensor.router_uptime')|int) / 60) | int }}
    router_up_time_days:
      friendly_name: 'Router uptime - Days'
      value_template: >-
        {{ ((states('sensor.router_up_time_hours')|int) / 24) | int }}

    wan_in_mb:
      value_template: >-
        {{ states('sensor.wan_in')|float/1000000 }}
    wan_out_mb:
      value_template: >-
        {{ states('sensor.wan_out')|float/1000000 }}
    wan_in_gb:
      value_template: >-
        {{ states('sensor.wan_in_mb')|float/1000 }}
    wan_out_gb:
      value_template: >-
        {{ states('sensor.wan_out_mb')|float/1000 }}
    wan_mb:
      value_template: >-
        {{ states('sensor.wan_in_mb')|float + states('sensor.wan_out_mb')|float }}
    wan_gb:
      value_template: >-
        {{ states('sensor.wan_in_gb')|float + states('sensor.wan_out_gb')|float }}

    internet_hourly:
      friendly_name: Hourly Internet Usage
      unit_of_measurement: MB
      value_template: >-
        {{ (states('sensor.utility_internet_hourly')|float)|round(2) }}
    internet_daily:
      friendly_name: Daily Internet Usage
      unit_of_measurement: GB
      value_template: >-
        {{ (states('sensor.utility_internet_daily')|float)|round(2) }}
    internet_monthly:
      friendly_name: Monthly Internet Usage
      unit_of_measurement: GB
      value_template: >-
        {{ (states('sensor.utility_internet_monthly')|float)|round(2) }}

    octoprint_print_time_done_at:
      value_template: >-
        {% if states('sensor.octoprint_print_time_left') is string -%}
          {% set times = states('sensor.octoprint_print_time_left').split(':') %}
            {% if times | length >= 3 -%}
              {% set seconds =  (times[0] | int) * 60 * 60 + (times[1] | int) * 60 + (times[2] | int) %}
              {{ (as_timestamp(now()) + seconds) | timestamp_local }}
            {%- endif %}
        {%- endif %}
      